(()=>{'use strict';
const $=id=>document.getElementById(id),fmt=n=>new Intl.NumberFormat('de-DE').format(n),pct=n=>new Intl.NumberFormat('de-DE',{maximumFractionDigits:1,minimumFractionDigits:1}).format(n)+' %',esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const EXT=/\.(xls|xlsx|xlsm|xlsb)$/i,DEFAULT='Armature_Nameplate_Check';
let sources=[],cache=new Map(),records=[],issues=[],lastScan=null,scanning=false,timer=null,demo=false,parserOK=false,lastFileCount=0,manualMode=false,persistenceError='',savedFilters=null,restoredSnapshot=false;
const CHECKS=new Map([[DEFAULT,'Namensprüfung'],['Armature_Basic_Check','Armature Basic'],['Armature_Smart_Check','Armature Smart']]);
function message(s,type=''){const el=$('status');el.textContent=s;el.className='status '+type;}
function loadParser(){if(window.XLSX?.read){parserOK=true;message('Bereit · Excel-Parser lokal geladen.','ok');scanAll(true);return;}message('Lade Excel-Parser …');let s=document.createElement('script');s.src='./xlsx.full.min.js';s.onload=()=>{parserOK=!!window.XLSX?.read;if(parserOK){message('Excel-Parser lokal verfügbar.','ok');scanAll(true);}else loadOnline()};s.onerror=loadOnline;document.head.appendChild(s)}
function loadOnline(){if(window.XLSX?.read){parserOK=true;return;}const s=document.createElement('script');s.src='https://cdn.sheetjs.com/xlsx-0.20.3/package/dist/xlsx.full.min.js';s.onload=()=>{parserOK=!!window.XLSX?.read;message(parserOK?'Excel-Parser geladen · Daten bleiben lokal.':'Excel-Parser konnte nicht gestartet werden.',parserOK?'ok':'err');if(parserOK)scanAll(true)};s.onerror=()=>message('Excel-Parser nicht erreichbar. Lege xlsx.full.min.js in den Dashboard-Ordner (siehe ANLEITUNG).','err');document.head.appendChild(s)}
// Folder handles, filters and an optional last-analysis snapshot remain in this browser profile.
// IndexedDB storage is bound to the URL origin (including the port): always use localhost:8765.
const dbOpen=()=>new Promise((res,rej)=>{if(!window.indexedDB){rej(Error('IndexedDB nicht verfügbar'));return;}const req=indexedDB.open('ship-check-dashboard-v2',2);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('roots'))db.createObjectStore('roots',{keyPath:'id'});if(!db.objectStoreNames.contains('state'))db.createObjectStore('state')};req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)});
async function dbStateWrite(key,value){const db=await dbOpen();try{await new Promise((res,rej)=>{const tx=db.transaction('state','readwrite');tx.objectStore('state').put(value,key);tx.oncomplete=res;tx.onerror=()=>rej(tx.error);tx.onabort=()=>rej(tx.error)})}finally{db.close()}}
async function dbStateRead(key){const db=await dbOpen();try{return await new Promise((res,rej)=>{const tx=db.transaction('state','readonly'),req=tx.objectStore('state').get(key);req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}finally{db.close()}}
function saveFilters(){const cfg={shipName:$('shipName').value,multiMode:$('multiMode').checked,ship:$('shipSelect').value,group:$('groupSelect').value,check:$('checkSelect').value,rank:$('rankBy').value,status:$('statusFilter').value};dbStateWrite('filters',cfg).catch(e=>console.warn('Filter konnten nicht gespeichert werden',e))}
async function saveSnapshot(){try{await dbStateWrite('snapshot',{cache:[...cache.entries()],lastFileCount,lastScan:lastScan?.toISOString()||null})}catch(e){console.warn('Letzte Analyse nicht speicherbar',e);persistenceError='Der zuletzt ausgewertete Stand konnte nicht lokal gespeichert werden.'}}
async function updatePermissionIndicators(){for(const src of sources){try{src.permission=await src.handle.queryPermission({mode:'read'})}catch(e){src.permission='unsupported'}}drawSources()}
async function reauthorize(s){try{const permission=await s.handle.requestPermission({mode:'read'});s.permission=permission;drawSources();if(permission==='granted'){manualMode=false;await scanAll(true)}else message('Ordner bleibt gespeichert. Für aktuelle Daten bitte Lesezugriff erlauben.','err')}catch(e){message('Berechtigung konnte nicht angefordert werden: '+e.message,'err')}}
async function dbSet(s){try{const db=await dbOpen();await new Promise((res,rej)=>{const t=db.transaction('roots','readwrite');t.objectStore('roots').put({id:s.id,ship:s.ship,mode:s.mode,handle:s.handle});t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close();persistenceError=''}catch(e){persistenceError='Ordner nur für diese Sitzung verbunden: '+e.message;message(persistenceError,'err')}}
async function dbDelete(id){try{const db=await dbOpen();await new Promise((res,rej)=>{const t=db.transaction('roots','readwrite');t.objectStore('roots').delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)});db.close()}catch(e){console.warn(e)}}
async function restore(){try{const db=await dbOpen();const old=await new Promise((res,rej)=>{const t=db.transaction('roots','readonly');const r=t.objectStore('roots').getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});db.close();sources=old.filter(s=>s?.handle?.kind==='directory');savedFilters=await dbStateRead('filters').catch(()=>null);if(savedFilters){$('shipName').value=savedFilters.shipName||'';$('multiMode').checked=!!savedFilters.multiMode;if(savedFilters.check)$('checkSelect').value=savedFilters.check;if(savedFilters.rank)$('rankBy').value=savedFilters.rank;if(savedFilters.status)$('statusFilter').value=savedFilters.status;}
const snap=await dbStateRead('snapshot').catch(()=>null);if(snap&&sources.length){cache=new Map(snap.cache||[]);records=[...cache.values()].flatMap(entry=>entry.records||[]);lastFileCount=snap.lastFileCount||0;lastScan=snap.lastScan?new Date(snap.lastScan):null;restoredSnapshot=records.length>0;}
render(false);if(savedFilters&&records.length){if(savedFilters.ship&&[...$('shipSelect').options].some(o=>o.value===savedFilters.ship))$('shipSelect').value=savedFilters.ship;buildFilters();if(savedFilters.group&&[...$('groupSelect').options].some(o=>o.value===savedFilters.group))$('groupSelect').value=savedFilters.group;draw()}
await updatePermissionIndicators();if(old.length)message(`Gespeichert: ${old.length} Ordner. ${restoredSnapshot?'Letzte Analyse wiederhergestellt; ':''}Bei Bedarf „Zugriff erneuern“ anklicken.`,'ok');}
catch(e){persistenceError='Gespeicherte Ordner konnten nicht wiederhergestellt werden: '+e.message;message(persistenceError,'err')}}
function drawSources(){const root=$('sources');root.innerHTML=sources.map(s=>{const label=s.permission==='granted'?'Zugriff aktiv':s.permission==='prompt'?'Zugriff nach Neustart bestätigen':s.permission==='denied'?'Zugriff gesperrt':'Berechtigung prüfen';return `<div class="source"><div class="row"><strong>${esc(s.mode==='multi'?'Schiffs-Überordner':s.ship)}</strong><button data-remove="${esc(s.id)}" title="Verbindung entfernen">×</button></div><small>${esc(s.handle?.name||'Ordner')} · ${s.mode==='multi'?'Unterordner = Schiff':'ein Schiff'}</small><div class="source-access">${esc(label)}${s.permission==='granted'?'':` <button class="btn" data-reauth="${esc(s.id)}">Zugriff erlauben</button>`}</div></div>`}).join('');root.querySelectorAll('[data-remove]').forEach(btn=>btn.onclick=async()=>{sources=sources.filter(s=>s.id!==btn.dataset.remove);await dbDelete(btn.dataset.remove);for(const key of [...cache.keys()])if(key.startsWith(btn.dataset.remove+'|'))cache.delete(key);records=[...cache.values()].flatMap(c=>c.records);await saveSnapshot();manualMode=false;render(true);await scanAll(true);drawSources()});root.querySelectorAll('[data-reauth]').forEach(btn=>btn.onclick=()=>{const s=sources.find(x=>x.id===btn.dataset.reauth);if(s)reauthorize(s)})}
function uid(){return String(Date.now())+'-'+String(Math.floor(Math.random()*1e8))}
$('connect').onclick=async()=>{if(!window.showDirectoryPicker){message('Für dauerhafte Ordnerverbindungen Edge oder Chrome über Start-Dashboard.bat verwenden.','err');return;}try{const handle=await window.showDirectoryPicker({id:'schiffsreports',mode:'read'});const mode=$('multiMode').checked?'multi':'single',ship=$('shipName').value.trim()||handle.name;if(mode==='single'&&sources.some(s=>s.mode==='single'&&s.ship===ship)){message('Für Schiff „'+ship+'“ existiert bereits eine Verbindung. Bitte zunächst entfernen oder eine andere Bezeichnung wählen.','err');return;}const root={id:uid(),ship,mode,handle,permission:'granted'};sources.push(root);drawSources();await dbSet(root);try{await navigator.storage?.persist?.()}catch(e){console.warn('Persistenter Browserspeicher nicht zugesagt',e)}manualMode=false;demo=false;saveFilters();await updatePermissionIndicators();await scanAll(true)}catch(e){if(e.name!=='AbortError')message('Ordnerzugriff fehlgeschlagen: '+e.message,'err')}};
$('reconnect').onclick=async()=>{if(!sources.length){message('Noch keine gespeicherten Ordnerverbindungen vorhanden.');return;}let ok=0;for(const s of sources){try{if(await s.handle.requestPermission({mode:'read'})==='granted')ok++}catch(e){console.warn(e)}}await updatePermissionIndicators();manualMode=false;demo=false;await scanAll(true);if(ok!==sources.length)message(`${ok} von ${sources.length} Ordnern freigegeben. Fehlende Ordner bleiben gespeichert.`,'err')};
$('rescan').onclick=()=>{manualMode=false;demo=false;scanAll(true)};
$('filesPick').onclick=()=>$('filesInput').click();$('filesInput').onchange=async e=>{const files=[...e.target.files];if(files.length)await loadOneOff(files)};
const drop=$('drop');drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');drop.ondrop=async e=>{e.preventDefault();drop.classList.remove('drag');let files=[];try{for(const item of [...e.dataTransfer.items]){const ent=item.webkitGetAsEntry?.();if(ent){await entryWalk(ent,files,'')}else{const f=item.getAsFile();if(f)files.push(f)}}}catch(err){console.warn(err)}if(!files.length)files=[...e.dataTransfer.files];await loadOneOff(files)};
async function entryWalk(ent,out,parent){if(ent.isFile){const f=await new Promise((res,rej)=>ent.file(res,rej));f.pathLabel=parent+f.name;out.push(f)}else if(ent.isDirectory){const reader=ent.createReader();while(true){const entries=await new Promise((res,rej)=>reader.readEntries(res,rej));if(!entries.length)break;for(const entry of entries)await entryWalk(entry,out,parent+ent.name+'/')}}}
async function loadOneOff(files){if(!parserOK){message('Excel-Parser noch nicht verfügbar (siehe ANLEITUNG).','err');return;}const ship=$('shipName').value.trim()||'Nicht zugeordnet',good=files.filter(f=>EXT.test(f.name)&&!f.name.startsWith('~$'));if(!good.length){message('Keine XLS-/XLSX-Dateien in der Auswahl.','err');return;}manualMode=true;demo=false;records=[];issues=[];scanning=true;for(let i=0;i<good.length;i++){const f=good[i];message(`Importiere ${i+1} / ${good.length}: ${f.name}`);const path=f.pathLabel||f.webkitRelativePath||f.name;try{const arr=await parseFile(f,ship,f.name,path);records.push(...arr)}catch(e){issues.push({file:path,reason:String(e.message||e)})}if(i%3===0)await new Promise(r=>setTimeout(r,0))}lastFileCount=good.length;lastScan=new Date();scanning=false;render(true);message(`${good.length} Excel-Dateien eingelesen · einmaliger Import ohne automatische Ordnerüberwachung.`,issues.length?'err':'ok')}
async function* walk(handle,prefix='',depth=0){if(depth>4)return;for await(const [name,entry] of handle.entries()){if(name.startsWith('~$'))continue;if(entry.kind==='file'&&EXT.test(name)){const file=await entry.getFile();yield {file,path:prefix+name}}else if(entry.kind==='directory')yield* walk(entry,prefix+name+'/',depth+1)}}
async function collect(){const found=[];const faults=[],blocked=new Set();for(const src of sources){let permission='prompt';try{permission=await src.handle.queryPermission({mode:'read'})}catch(e){faults.push({file:src.handle.name,reason:'Berechtigung nicht abrufbar: '+e.message});blocked.add(src.id);continue}src.permission=permission;if(permission!=='granted'){faults.push({file:src.handle.name,reason:'Zugriff benötigt · „Zugriff erlauben“ anklicken (Verbindung ist weiterhin gespeichert)'});blocked.add(src.id);continue;}try{for await(const item of walk(src.handle)){const rel=item.path;let ship=src.ship;if(src.mode==='multi'){const seg=rel.split('/');if(seg.length<2){faults.push({file:rel,reason:'Datei liegt im Überordner und ist keinem Schiff zugeordnet.'});continue;}ship=seg[0];}found.push({...item,ship,srcid:src.id})}}catch(e){faults.push({file:src.handle.name,reason:'Ordner konnte nicht gelesen werden: '+e.message});blocked.add(src.id)}}return {found,faults,blocked}}
async function scanAll(force=false){if(!parserOK||scanning||demo||manualMode)return;if(!sources.length){records=[];issues=[];lastFileCount=0;lastScan=null;render(true);return;}scanning=true;let totalChanged=0;try{const {found,faults,blocked}=await collect();issues=faults;lastFileCount=found.length+[...cache.keys()].filter(key=>blocked.has(key.split('|')[0])).length;drawSources();const active=new Set();for(let i=0;i<found.length;i++){const obj=found[i],key=obj.srcid+'|'+obj.path,signature=obj.file.lastModified+'|'+obj.file.size+'|'+obj.ship;active.add(key);if(cache.get(key)?.signature===signature)continue;totalChanged++;message(`Prüfe ${i+1} von ${found.length}: ${obj.file.name}`);try{const result=await parseFile(obj.file,obj.ship,obj.file.name,obj.path);cache.set(key,{signature,records:result,error:null})}catch(e){cache.set(key,{signature,records:[],error:String(e.message||e)})}if(i%3===0)await new Promise(r=>setTimeout(r,0))}for(const key of [...cache.keys()])if(!active.has(key)&&!blocked.has(key.split('|')[0]))cache.delete(key);records=[];for(const [key,c] of cache){records.push(...c.records);if(c.error)issues.push({file:key.split('|').slice(1).join('|'),reason:c.error})}if(!blocked.size){lastScan=new Date();restoredSnapshot=false;}else restoredSnapshot=true;render(false);await saveSnapshot();message(blocked.size?`Gespeicherte Ordner: ${blocked.size} benötigen erneut Zugriff. Letzter verfügbarer Stand wird angezeigt; dieser kann veraltet sein.`:`Überwachung aktiv · ${found.length} Excel-Dateien · ${fmt(records.length)} Armaturen-Fundstellen · ${totalChanged} neu oder verändert.`+(issues.length?` ${issues.length} Hinweis(e).`:''),blocked.size||issues.length?'err':'ok')}catch(e){message('Aktualisierung fehlgeschlagen: '+e.message,'err')}finally{scanning=false}}
const clean=s=>String(s??'').trim(),norm=s=>clean(s).toLowerCase().replace(/[^a-z0-9]/g,'');
const findHeader=(array)=>{for(let i=0;i<Math.min(16,array.length);i++){const row=array[i].map(norm);const ty=row.findIndex(s=>s==='type'||s==='objekttyp'),dn=row.findIndex(s=>s==='displayname'||s==='armaturennummer');if(ty>=0&&dn>=0){const map={type:ty,name:dn,path:row.findIndex(s=>s==='objectpath'||s==='objektpfad'),checks:[]};array[i].forEach((cell,col)=>{const raw=clean(cell);if(/_check/i.test(raw)||/check/i.test(raw)&&col>=4){map.checks.push({col,original:raw,key:canonical(raw)})}});if(!map.checks.length&&array[i].length>6){map.checks=[{col:4,original:'Armature_Basic_Check',key:'Armature_Basic_Check'},{col:5,original:'Armature_Smart_Check',key:'Armature_Smart_Check'},{col:6,original:DEFAULT,key:DEFAULT}]}return {index:i,map}}}return null};
function canonical(raw){const n=norm(raw);if(n.includes('armature')&&n.includes('nameplate'))return DEFAULT;if(n.includes('armature')&&n.includes('basic'))return 'Armature_Basic_Check';if(n.includes('armature')&&n.includes('smart'))return 'Armature_Smart_Check';return raw}
async function parseFile(file,ship,name,path){const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false,cellText:true});let target=null;for(const sn of wb.SheetNames){const sh=wb.Sheets[sn];if(!sh?.['!ref'])continue;const arr=XLSX.utils.sheet_to_json(sh,{header:1,raw:false,defval:'',blankrows:true});const header=findHeader(arr);if(header){target={arr,...header,sheet:sn,rowOffset:XLSX.utils.decode_range(sh['!ref']).s.r};break}}if(!target)throw Error('Kein gültiger Bericht: Spalten Type und DisplayName im Kopfbereich nicht gefunden.');const {arr,index,map,sheet,rowOffset}=target;for(const check of map.checks)if(check.key&&!CHECKS.has(check.key))CHECKS.set(check.key,check.original);const group=(name.replace(/\.(xls|xlsx|xlsm|xlsb)$/i,'').match(/DiagramCheck[_-]*(.+)$/i)||[])[1]||name.replace(/\.(xls|xlsx|xlsm|xlsb)$/i,'');const output=[];for(let i=index+1;i<arr.length;i++){const row=arr[i]||[],type=clean(row[map.type]);if(!/^armatur(e)?$/i.test(type))continue;const id=clean(row[map.name]),obj=map.path<0?'':clean(row[map.path]);if(!id&&!obj)continue;const checks={};for(const f of map.checks)checks[f.key]=clean(row[f.col]);output.push({ship,group:String(group),id,path:obj,checks,file:path,sheet,row:i+1+rowOffset})}return output}
const isNameplate=key=>key===DEFAULT;
function getState(row,key){const raw=clean(row.checks[key]);if(!raw)return 'unchecked';if(/^ok$/i.test(raw))return 'ok';if(isNameplate(key)&&/name\s*must\s*be\s*filled\s*for\s*nameplate/i.test(raw))return 'bad';if(isNameplate(key))return 'other';return 'bad'}
function buildUnique(items,check){const m=new Map();const duplicates=[];for(const r of items){const key=r.ship+'\u241F'+(r.id.toUpperCase()||r.file+'|'+r.row);const s=getState(r,check);if(!m.has(key)){m.set(key,{...r,state:s,count:1});continue;}const existing=m.get(key);existing.count++;duplicates.push(r);const precedence={ok:0,unchecked:1,other:2,bad:3};if(precedence[s]>precedence[existing.state]){existing.state=s;existing.checks=r.checks;existing.file=r.file;existing.row=r.row;existing.path=r.path}}return {unique:[...m.values()],duplicates}}
function scopedRows(){const ship=$('shipSelect').value,group=$('groupSelect').value;return records.filter(r=>(ship==='ALL'||r.ship===ship)&&(group==='ALL'||r.ship+'\u241F'+r.group===group))}
function buildFilters(reset=false){const prevShip=reset?'ALL':$('shipSelect').value,ships=[...new Set(records.map(r=>r.ship))].sort((a,b)=>a.localeCompare(b,'de',{numeric:true}));$('shipSelect').innerHTML='<option value="ALL">Alle Schiffe</option>'+ships.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');$('shipSelect').value=ships.includes(prevShip)?prevShip:(ships.length===1?ships[0]:'ALL');const ps=reset?'ALL':$('groupSelect').value;const groups=[...new Set(records.filter(r=>$('shipSelect').value==='ALL'||r.ship===$('shipSelect').value).map(r=>r.ship+'\u241F'+r.group))].sort((a,b)=>a.localeCompare(b,'de',{numeric:true}));$('groupSelect').innerHTML='<option value="ALL">Alle Baugruppen</option>'+groups.map(s=>`<option value="${esc(s)}">${esc(s.replace('\u241F',' · '))}</option>`).join('');$('groupSelect').value=groups.includes(ps)?ps:'ALL';const chosen=$('checkSelect').value;$('checkSelect').innerHTML=[...CHECKS].map(([key,caption])=>`<option value="${esc(key)}">${esc(caption)}</option>`).join('');$('checkSelect').value=CHECKS.has(chosen)?chosen:DEFAULT}
function statsFrom(rows,check){const {unique,duplicates}=buildUnique(rows,check);const stats={total:unique.length,ok:0,bad:0,unchecked:0,other:0,unique,duplicates};for(const r of unique)stats[r.state]++;return stats}
function render(reset=false){buildFilters(reset);draw()}
function draw(){const check=$('checkSelect').value,isName=isNameplate(check),items=scopedRows(),st=statsFrom(items,check),total=st.total,$id=id=>$(id);const selectedGroup=$('groupSelect').value,ship=$('shipSelect').value;$id('scopeTitle').textContent=selectedGroup!=='ALL'?`Baugruppe ${selectedGroup.split('\u241F')[1]}`:ship!=='ALL'?`Schiff ${ship}`:'Gesamtübersicht';$id('loadedAt').textContent=lastScan?(restoredSnapshot?'Zwischengespeicherter Stand vom ':'Zuletzt geprüft ')+lastScan.toLocaleString('de-DE'):'Keine Dateien eingelesen';$id('topBadge').textContent=demo?'DEMO · Beispielwerte':sources.length?`Automatischer Abgleich · ${sources.length} Ordner`:`${lastFileCount} Berichte geladen`;
$id('total').textContent=fmt(total);$id('ok').textContent=fmt(st.ok);$id('bad').textContent=fmt(st.bad);$id('unchecked').textContent=fmt(st.unchecked);$id('rate').textContent=total?pct(100*st.ok/total):'—';$id('okTitle').textContent=isName?'Name vorhanden':'Prüfung OK';$id('badTitle').textContent=isName?'Name fehlt':'Prüfung fehlerhaft';$id('badSub').textContent=total?pct(100*st.bad/total)+' aller Armaturen':'Anteil an allen Armaturen';$id('rateTitle').textContent=isName?'Namensabdeckung':'OK-Anteil';$id('rateSub').textContent='OK / alle Armaturen';$id('pieTitle').textContent=isName?'Namensstatus':'Prüfstatus · '+(CHECKS.get(check)||check);$id('donutText').textContent=isName?'Name vorhanden':'OK';$id('donutPct').textContent=total?pct(100*st.ok/total):'—';
const slices=[['ok','#159476',isName?'Name vorhanden':'OK'],['bad','#db635c',isName?'Name fehlt':'Fehler'],['unchecked','#a4aebc','Ungeprüft'],['other','#e8a646','Andere Meldungen']];let start=0;const segments=[];for(const [key,color] of slices){if(!total||!st[key])continue;const end=start+100*st[key]/total;segments.push(`${color} ${start.toFixed(5)}% ${end.toFixed(5)}%`);start=end}$id('donut').style.background=segments.length?'conic-gradient('+segments.join(',')+')':'#e8edf4';$id('legend').innerHTML=slices.map(([k,c,label])=>`<div class="legend-item"><span class="dot" style="background:${c}"></span><span>${label}</span><b>${fmt(st[k])}</b></div>`).join('');$id('otherNote').textContent=st.other?'Hinweis: Andere Nameplate-Meldungen werden nicht automatisch als fehlende Namen eingestuft.':'';
const groupMap=new Map();for(const r of records.filter(r=>ship==='ALL'||r.ship===ship)){const k=r.ship+'\u241F'+r.group;if(!groupMap.has(k))groupMap.set(k,[]);groupMap.get(k).push(r)}const list=[...groupMap].map(([key,rows])=>({key,s:statsFrom(rows,check)}));const rank=$('rankBy').value;list.sort((a,b)=>rank==='percent'?(b.s.total?b.s.bad/b.s.total:0)-(a.s.total?a.s.bad/a.s.total:0):rank==='name'?a.key.localeCompare(b.key,'de',{numeric:true}):b.s.bad-a.s.bad||a.key.localeCompare(b.key,'de',{numeric:true}));$id('groupCount').textContent=fmt(list.length)+' Baugruppen';const peak=Math.max(1,...list.map(x=>rank==='percent'?(x.s.total?100*x.s.bad/x.s.total:0):x.s.bad));$id('barList').innerHTML=list.length?list.map(x=>{const p=x.s.total?100*x.s.bad/x.s.total:0;const name=x.key.replace('\u241F',' · ');return `<div class="barrow ${selectedGroup===x.key?'active':''}" data-group="${esc(x.key)}" title="${esc(name)} · ${fmt(x.s.bad)} von ${fmt(x.s.total)} · ${pct(p)}"><span class="barlabel">${esc(name)}</span><div class="barbg"><div class="barfill" style="width:${(rank==='percent'?p/peak:x.s.bad/peak)*100}%"></div></div><span class="barnum">${fmt(x.s.bad)}/${fmt(x.s.total)} · ${pct(p)}</span></div>`}).join(''):'<div class="center">Keine Diagramme im gewählten Bereich.</div>';$id('barList').querySelectorAll('[data-group]').forEach(el=>el.onclick=()=>{$('groupSelect').value=el.dataset.group;draw()});
$id('sourcesStats').textContent=`${fmt(lastFileCount)} Excel-Berichte eingelesen · ${fmt(records.length)} Armaturen-Fundstellen · ${fmt(new Set(records.map(r=>r.ship)).size)} Schiffe · ${fmt(new Set(records.map(r=>r.ship+'|'+r.group)).size)} Baugruppen.`;
const dupeCount=st.duplicates.length;const qualityWarnings=[];if(dupeCount)qualityWarnings.push(`${fmt(dupeCount)} zusätzliche Fundstellen mit bereits vorkommender Armaturennummer im gewählten Bereich.`);if(persistenceError)qualityWarnings.push(persistenceError);if(restoredSnapshot)qualityWarnings.push('Ein oder mehrere Ordner sind nicht frisch geprüft; gespeicherte Werte können veraltet sein.');if(issues.length)qualityWarnings.push(`${fmt(issues.length)} Datei-/Berechtigungshinweise: ${issues.slice(0,3).map(x=>x.file+': '+x.reason).join(' | ')}`);if(isName&&st.other)qualityWarnings.push(`${fmt(st.other)} Armaturen mit anderen Nameplate-Meldungen.`);if(!total&&lastFileCount)qualityWarnings.push('Keine Armaturen gefunden. Berichtkopf, Dateiaufbau und gewählten Schiff-Filter prüfen.');$id('warnings').textContent=qualityWarnings.join(' ')||'Keine Auffälligkeiten.';
renderTable();$id('exportVisible').disabled=!records.length;$id('exportBad').disabled=!records.length;}
function filtered(){const check=$('checkSelect').value,needle=$('search').value.toLocaleLowerCase('de'),stat=$('statusFilter').value;return scopedRows().filter(r=>{const status=getState(r,check);if(stat!=='ALL'&&status!==stat)return false;return !needle||[r.ship,r.group,r.id,r.path,r.file,clean(r.checks[check])].some(x=>String(x).toLocaleLowerCase('de').includes(needle))})}
function renderTable(){const check=$('checkSelect').value,rows=filtered(),tbody=$('tbody');$('listDesc').textContent=$('statusFilter').value==='bad'?(isNameplate(check)?'Fundstellen mit fehlendem Namen':'Fundstellen mit fehlerhafter Prüfung'):'Gefilterte Fundstellen';const show=rows.slice(0,500);tbody.innerHTML=show.map(r=>{const s=getState(r,check),text=s==='bad'?(isNameplate(check)?'Name fehlt':'Prüffehler'):s==='ok'?'OK':s==='unchecked'?'Ungeprüft':'Andere Meldung';return `<tr><td>${esc(r.ship)}</td><td>${esc(r.group)}</td><td><b>${esc(r.id||'—')}</b></td><td><span class="tag ${s==='ok'?'green':s==='bad'?'':'gray'}">${text}</span></td><td class="${s==='bad'?'errline':''}">${esc(r.checks[check]||'—')}</td><td class="path" title="${esc(r.path)}">${esc(r.path)}</td><td>${fmt(r.row)}</td><td title="${esc(r.file)}">${esc(r.file.split('/').pop())}</td></tr>`}).join('')||'<tr><td colspan="8" class="center">Für diese Filterung gibt es keine Fundstellen.</td></tr>';$('visibleCount').textContent=`${fmt(rows.length)} Fundstellen · ${fmt(show.length)} angezeigt${rows.length>500?' (CSV enthält alle gefilterten Treffer)':''}`}
function csvField(v){let s=String(v??'');if(/^[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"'}
function exportCSV(rows,check,name){const cols=['Schiff','Baugruppe','Armaturennummer','Status','Prüfmeldung','Objektpfad','Zeile','Datei','Tabellenblatt'];const table=[cols,...rows.map(r=>[r.ship,r.group,r.id,getState(r,check),r.checks[check],r.path,r.row,r.file,r.sheet])];const blob=new Blob(['\ufeff'+table.map(row=>row.map(csvField).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000)}
const exportName=kind=>{const safe=v=>String(v).replace(/[^a-z0-9_-]/gi,'_');return `Schiff_${safe($('shipSelect').value)}_Baugruppe_${safe($('groupSelect').value.replace('\u241F','_'))}_${safe($('checkSelect').value)}_${kind}.csv`};
$('exportVisible').onclick=()=>exportCSV(filtered(),$('checkSelect').value,exportName('gefiltert'));$('exportBad').onclick=()=>exportCSV(scopedRows().filter(r=>getState(r,$('checkSelect').value)==='bad'),$('checkSelect').value,exportName('alle_Fehler'));
$('shipSelect').onchange=()=>{buildFilters();draw();saveFilters()};$('groupSelect').onchange=()=>{draw();saveFilters()};$('checkSelect').onchange=()=>{draw();saveFilters()};$('rankBy').onchange=()=>{draw();saveFilters()};$('statusFilter').onchange=()=>{renderTable();saveFilters()};$('shipName').onchange=saveFilters;$('multiMode').onchange=saveFilters;$('search').oninput=renderTable;
$('demo').onclick=()=>{if(sources.length&&!confirm('Beispieldaten ersetzen die aktuelle Anzeige vorübergehend. Fortfahren?'))return;demo=true;manualMode=false;issues=[];records=[];for(const [ship,group,states] of [['713','768',['OK','OK','- Name must be filled for Nameplate','OK','- Name must be filled for Nameplate','OK']],['713','769',['OK','- Name must be filled for Nameplate','- Name must be filled for Nameplate','','OK']],['713','771',['OK','OK','OK','OK','OK']],['714','782',['OK','','- Name must be filled for Nameplate','OK']]]){states.forEach((s,i)=>records.push({ship,group,id:`${ship}A${group}${String(i+1).padStart(3,'0')}`,path:`${ship}---DIAGRAM/ValveSafety_Log_Ins-${group}${i}`,checks:{[DEFAULT]:s,Armature_Basic_Check:i===0?'Check issue':'OK',Armature_Smart_Check:'OK'},file:`DiagramCheck_${group}.xls`,sheet:'Report',row:i+3}))}lastFileCount=4;lastScan=new Date();$('shipSelect').value='ALL';render(true);message('DEMO: Es werden ausschließlich künstliche Beispieldaten angezeigt. Für echte Kennzahlen einen Ordner verbinden.');};
render(true);restore().finally(loadParser);timer=setInterval(()=>scanAll(),30000);
})();
